version: '3'
services:
  mysql:
    image: mysql
    ports:
      - "5432:5432"
  elasticsearch:
    image: elasticsearch
    # ports:
      # - "9200:9200"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - elasticsearch
